Cargo: add missing x500 feature
This was being ref'd in `oid_db.rs`, producing a clippy error of the
form:

```
error: unexpected `cfg` condition value: `x500`
   --> /home/runner/work/oid-registry/oid-registry/target/debug/build/oid-registry-fa6fec30f9e743c7/out/oid_db.rs:411:11
    |
411 |     #[cfg(feature = "x500")]
    |           ^^^^^^^^^^------
    |                     |
    |                     help: there is a expected value with a similar name: `"x509"`
    |
    = note: expected values for `feature` are: `crypto`, `default`, `kdf`, `ms_spc`, `nist_algs`, `pkcs1`, `pkcs12`, `pkcs7`, `pkcs9`, `registry`, `x509`, and `x962`
```